### ISSUE TITLE
UI should have "Pause/Resume" for scenario sessions

### ISSUE THREAD

**Issue by Oats87** [hobbyfarm/ui#15]
The UI should have a "Pause/Resume" button for scenario sessions which allows users to freeze their scenarios.

Relies on: https://github.com/hobbyfarm/gargantua/issues/8

**Comment by Oats87** [comment]
this is semi-done, it should only show if the scenario is pauseable (may require API change)

**Comment by Oats87** [comment]
@ebauman this isn't fully completed yet

**Comment by ebauman** [comment]
@Oats87 Take a peek at the commit. There's a new `ngIf` added to not show the pause button if the Scenario object has that property set to `false`
