### ISSUE TITLE
No option to insecurely connect to backend

### ISSUE THREAD

**Issue by hall** [hobbyfarm/ui#34]
The connection protocol for the backend service is currently hardcoded; for example, as [https](https://github.com/hobbyfarm/ui/tree/0b70825111009b643732a45b308f7b13e8ed2dd3/src/app/services/scenario.service.ts#L20) and [wss](https://github.com/hobbyfarm/ui/tree/0b70825111009b643732a45b308f7b13e8ed2dd3/src/app/scenario/terminal.component.ts#L53).

This make it difficult to run the stack locally, where connections are insecure. Instead, the protocol can be read from the environment (prepended to the hostname) or an `--insecure` flag can be created.

Let me know if you have a preference and I'll open a PR.

**Comment by ebauman** [comment]
I think this should be implemented as a flaggable option. 
It would be nice to potentially connect insecurely e.g. when using `k3s` local dev. 

If you'd like to PR for this that would be amazing - there's an example of how I'm doing string replacement for "flag injection" if you look in `src/environments/environment.ts`.

Basically putting that placeholder in, and applying `sed` when executing `entrypoint.sh`. 

Perhaps something similar to be done for this? i.e. set desired protocols as configurable options for http and websocket.

**Comment by hall** [comment]
Sounds good to me; thanks for the pointers! I'll aim to get a PR opened sometime next week.

**Comment by ebauman** [comment]
Thank you!!
